name: test_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  solid_lints: ^0.0.14

flutter:
  uses-material-design: true
  fonts:
    - family: Bariol
      fonts:
        - asset: fonts/Bariol.ttf